### ISSUE TITLE
Cannot be used with lazily-loaded engines in dev mode

### ISSUE THREAD

**Issue by sohara** [ivanvotti/ember-svg-jar#44]
We've run into an issue where we cannot navigate to our lazily load (in-repo) engines when in development mode. 1

This is because the asset-loading service behind ember-engines constructs a manifest file based on what it sees as the engine's trees/assets. For some reason it's adding ember-svg-jar assets as well, and when loaded we get a console error:
```sh
Could not read config from meta tag with name "svg-jar/config/environment".
```
I've created a repo with the repo case here (error occurs when clicking the `Users` link):
https://github.com/sohara/svg-jar-lazy-engine

**Comment by ivanvotti** [comment]
The bug is fixed in the latest `ember-svg-jar v1.X.X`. Feel free to reopen the issue if you still can reproduce it.

**Comment by mallikarjun1234** [comment]
@sohara I am using the latest ember-svg-jar v1.X.X and ember-cli v.2.12 , but then {{svg-jar}} doesn't seem to be working in IN-REPO-ENGINE. I still get the error 'Could not read config from meta tag with name "svg-jar/config/environment"'. Is it really necessary to use ember v.3.0. Can we any way achieve a solution using ember cli v.2.12
